name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  trigger-jenkins:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Jenkins Build
        id: jenkins
        uses: appleboy/jenkins-action@v1.0.0
        with:
          jenkins_url: ${{ secrets.JENKINS_URL }}
          jenkins_user: ${{ secrets.JENKINS_USER }}
          jenkins_token: ${{ secrets.JENKINS_TOKEN }}
          job: "YOUR_JENKINS_JOB_NAME"
          token: "YOUR_JENKINS_JOB_TOKEN"

      - name: Merge Pull Request
        if: success()
        uses: actions/github-script@v3
        with:
          script: |
            const { data: pullRequest } = await github.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
            });

            if (pullRequest.state === 'open' && pullRequest.mergeable) {
              await github.pulls.merge({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: pullRequest.number,
              });
            }
